plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jemoji

remote_theme: "mmistakes/minimal-mistakes@4.15.1"
minimal_mistakes_skin    : "dark"

locale                   : "en-US"
title                    : "Useful links"
description              : "Site to save useful links"
logo                     : #

include:
  - _pages
markdown: kramdown
search: true

collections:
  web:
    output: true
    permalink: /:collection/:path/
  pwn:
    output: true
    permalink: /:collection/:path/
  re:
    output: true
    permalink: /:collection/:path/
  crypto:
    output: true
    permalink: /:collection/:path/
  misc:
    output: true
    permalink: /:collection/:path/


defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: collection
      classes: wide
  # _web
  - scope:
      path: ""
      type: web
    values:
      layout: single
      classes: wide
      header:
        overlay_color: "#008288"
        overlay_filter: 0.5
  # _pwn
  - scope:
      path: ""
      type: pwn
    values:
      layout: single
      classes: wide
      header:
        overlay_color: "#008288"
        overlay_filter: 0.5
  # _re
  - scope:
      path: ""
      type: re
    values:
      layout: single
      classes: wide
      header:
        overlay_color: "#008288"
        overlay_filter: 0.5
  # _crypto
  - scope:
      path: ""
      type: crypto
    values:
      layout: single
      classes: wide
      header:
        overlay_color: "#008288"
        overlay_filter: 0.5
  # _misc
  - scope:
      path: ""
      type: misc
    values:
      layout: single
      classes: wide
      header:
        overlay_color: "#008288"
        overlay_filter: 0.5
