plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: "mmistakes/minimal-mistakes@4.15.1"
minimal_mistakes_skin    : "dark"

locale                   : "en-US"
title                    : "Useful links"
description              : "Site to save useful links"
logo                     : #

include:
  - _pages
markdown: kramdown

collections:
  web:
    output: true
    permalink: /:collection/:path/
  pwn:
    output: true
    permalink: /:collection/:path/


defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
  # _web
  - scope:
      path: ""
      type: web
    values:
      layout: single
  # _pwn
  - scope:
      path: ""
      type: pwn
    values:
      layout: single
